spring:
  application:
    name: springboot-testing
  datasource:
    url: jdbc:h2:mem:testdb
    username: ""
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
server:
  port: 9000
